name: CI Tests/Lints

on:
  push:
    paths:
      - "termynal/**"
      - "tests/**"
      - "poetry.lock"
    branches: [ main ]
  pull_request:
    paths:
      - "termynal/**"
      - "tests/**"
      - "poetry.lock"
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.1'

      - name: Install poetry
        run: pip install poetry==1.3.2

      - name: Install python dependencies
        run: make install

      - name: Run linters
        run: make lint

      - name: Run test
        run: make test
